#!/usr/bin/env bash
set -e

for x; do
  if output=$("$x"); then
    echo "ok - ${x##*/}"
  else
    echo "not ok - ${x##*/}"
    echo "$output"
    exit 1
  fi &

  if [[ $SETH_PARALLEL ]]; then
    pids+=($!)
  else
    wait
  fi
done

if [[ $SETH_PARALLEL ]]; then
  for pid in "${pids[@]}"; do wait "$pid"; done
fi
