#!/usr/bin/env bash
### seth-calldata -- pack function names and arguments into calldata
### Usage: seth calldata <sig> [<args>]
###    or: seth calldata [<hexdata>]
###
### Pack <sig> and <args> into data suitable for passing to `seth call'.
###
### The <sig> needs to look like `<name>(<in-types>)[(<out-types>)]'.
### The <out-types> are ignored and can be omitted altogether.
###
### If <sig> is given but is not valid, treat it as <hexdata> instead.
### If no arguments are given, read <hexdata> from standard input instead.
set -e
if [[ $1 =~ ^([^\[\(]+)[\(\[] ]]; then
  name=${BASH_REMATCH[1]}
  abi=$(seth --abi-json "$1")
  shift; for x; do args+=(-p "${x#0x}"); done
  calldata=$(
    [[ $SETH_DEBUG_ETHABI ]] && set -x
    ethabi encode function <(echo "$abi") "$name" "${args[@]}" -l
  )
  if [[ $calldata = error* ]]; then
    echo >&2 "ethabi: $calldata"
    exit 1
  else
    echo "0x${calldata#0x}"
  fi
elif [[ $2 ]]; then
  seth --bad-usage "$0"
else
  seth --to-hexdata "$@"
fi
