#!/usr/bin/env bash
### seth-block -- print general or specific information about a block
### Usage: seth block [<block>] [<field>]
### Show information about <block> (a number, a hash or `latest').
###
### If no <block> is given, display blockchain sync status instead.
### If <field> is given, print only that piece of information.
### If no <field> is given, show all the fields in a big table.
set -e
[[ $3 ]] && seth --bad-usage "$0"
[[ $1 ]] || exec seth block-number
block=$(seth get-block-by-number "$1")
[[ $block = null ]] && seth --error "$0" "no such block: $1"
[[ $2 ]] && exec seth --field "$2" <<<"$block"
echo "$block"
