#!/usr/bin/env bash
set -e
[[ $1 ]] || set -- "`cat`"

if [[ $1 =~ ^0x[[:xdigit:]]+$ ]]; then
  echo ${1,,}
elif [[ $1 =~ ^[[:xdigit:]]+$ ]]; then
  echo 0x${1,,}
else  
  echo >&2 "${0##*/}: error: invalid hexdata: \`$1'"
  exit 1
fi
