#!/usr/bin/env bash
file=${0%/*}/seth${1+-$1}
header=$(grep -oP '^(\S)\1\1( \K.*)?' "$file" | perl -pe 's/^(\S)\1\1$//')

if ! [[ $header ]]; then
  sed "s/^/${0##*/}: /" "$file"
elif [[ `wc -l <<<"$header"` = 1 ]]; then
  echo "$header"
else
  sed 1d <<<"$header"
fi

if ! [[ $1 ]]; then
  for file in `dirname $0`/seth-*; do
    if [[ -L $file ]]; then
      continue
    elif [[ $file = */seth---* ]]; then
      utils+=("$file")
    else
      commands+=("$file")
    fi
  done

  list-commands() {
    grep -hoP "^(\\S)\\1\\1 seth-\\K[^ ]* -- .*" "$@" |
    sed "s/ -- / /" | while read name label; do
      printf "   %-12s  %s\n" "$name" "$label"
    done | LANG=C sort
  }

  cat <<.

Special commands:

$(list-commands "${utils[@]}")

Commands:

$(list-commands "${commands[@]}")

Report bugs to <https://github.com/nexusdev/seth>.
.
fi
