#!/usr/bin/env bash
### seth-calldata -- pack function name and arguments into calldata
### Usage: seth calldata <name>(<inputs>)(<outputs>) [<args>...]
###    or: seth calldata [<calldata>]

set -e
if [[ $1 =~ ^([^\[\(]+)[\(\[] ]]; then
  name=${BASH_REMATCH[1]}
  for arg in "${@:2}"; do args+=(-p "$arg"); done
  abi=`seth --abi-json "$1"`
  calldata=`ethabi encode function <(echo "$abi") "$name" "${args[@]}" -l`
  if [[ $calldata = error* ]]; then
    echo >&2 "ethabi: $calldata"
    exit 1
  else
    echo 0x${calldata#0x}
  fi
elif ! [[ $2 ]]; then
  seth --to-hexdata "$@"
else
  seth calldata --help >&2
  exit 1
fi
