#!/usr/bin/env bash
set -e

if [[ $# = 0 ]]; then
  set -- "$(cat)"
elif [[ $# != 1 ]]; then
  echo >&2 "Usage: ${0##*/} <hexdata>"
  exit 1
fi    

if [[ $1 = @* ]]; then
  value=$(seth --lookup "$1")
  "$0" "$value"
elif [[ $1 =~ ^0x[[:xdigit:]]+$ ]]; then
  echo "${1,,}"
elif [[ $1 =~ ^[[:xdigit:]]+$ ]]; then
  echo "0x${1,,}"
else
  first=${1:0:20} rest=${1:21}
  echo >&2 "${0##*/}: error: invalid hexdata: \`$1'"
  exit 1
fi
