#!/usr/bin/env bash
### seth-mktx -- construct a signed transaction using ethsign
### Usage: seth mktx [<opts>] [-F <from>] <to> <sig> [<args>]
###    or: seth mktx [<opts>] [-F <from>] <to> <calldata> [<args>]
set -e
[[ $ETH_KEYSTORE ]] ||
seth --fail "${0##*/}: error: \`ETH_KEYSTORE' not set"
[[ -f $ETH_PASSWORD ]] ||
seth --fail "${0##*/}: error: \`ETH_PASSWORD' file not present"

[[ $1 ]] && [[ $ETH_FROM ]] || seth --fail-usage "$0"

value=$(seth --to-wei ${ETH_VALUE:-0})
value=$(seth --to-hex $value)
if [[ $2 ]]; then
  data=$(seth calldata "${@:2}")
fi

args=(
  --key-store $ETH_KEYSTORE
  --from $(seth --to-address $ETH_FROM)
  --passphrase-file $ETH_PASSWORD
  --nonce $(seth nonce $ETH_FROM)
  --chain-id $(seth rpc net_version)
  --to $(seth --to-address "$1")
  --gas-price ${ETH_GAS_PRICE:-$(seth gas-price)}
  --gas-limit ${ETH_GAS:-200000}
  --value $value
  --data ${data:-0x}
)
tx=$(ethsign tx "${args[@]}")
echo $tx
