#!/usr/bin/env bash
### seth-block -- print general or specific information about a block
set -e
[[ $1 ]] || exec seth syncing
[[ $3 ]] && { seth block --help >&2; exit 1; }
### Usage: seth block [<block>] [<field>]
### Show information about <block> (default: `latest').
block=$(seth get-block-by-number "$1")
###
### If <field> is given, print only that piece of information.
[[ $block != null && $2 ]] && exec <<<"$block" seth --field "$2"
### If no <field> is given, print all the fields in a big table.
[[ $block != null ]] && exec <<<"$block" cat
echo >&2 "${0##*/}: error: no such block: $1"
exit 1
