#!/usr/bin/env bash
set -e
result=$(seth --jsonrpc eth_syncing)
if [[ $result != false ]]; then
  b0=$(seth --field <<<"$result" startingBlock)
  b1=$(seth --field <<<"$result" highestBlock)
  b=$(seth --field <<<"$result" currentBlock)
  echo $((b))/$((b1)) [$(((b - b0) * 100 / (b1 - b0)))%]
else
  seth number
fi
