#!/usr/bin/env bash
set -e
### seth---abi-json -- print the ABI of a function in standard JSON format
### Usage: seth --abi-json <sig>

if ! [[ $1 =~ ^([^\(]+)\(([^\(]*)\)(\(([^\(]*)\))?$ ]]; then
  echo >&2 "${0##*/}: error: bad signature: $1"
  exit 1
fi

name=${BASH_REMATCH[1]}
input_types=${BASH_REMATCH[2]//,/ }
output_types=${BASH_REMATCH[4]//,/ }

for type in $input_types; do
  inputs_jshon+=(-n {} -s "x$((++n))" -i name -s "$type" -i type -i append)
done

for type in $output_types; do
  outputs_jshon+=(-n {} -s "x$((++n))" -i name -s "$type" -i type -i append)
done

jshon <<<[] -n {} \
-s "$name" -i name -s function -i type \
-n [] "${inputs_jshon[@]}" -i inputs \
-n [] "${outputs_jshon[@]}" -i outputs \
-i append
