#!/usr/bin/env bash
### seth-balance -- show the balance of any account on the blockchain
### Usage: seth balance [-B <block>] <account>
### Print the balance of <account> in ETH.
###
### With `-B <block>', print the balance as of <block>.
set -e
[[ $1 ]] || seth --bad-usage "$0"
account=$1
[[ $account = @* ]] && account=$(seth --lookup "$account")
jshon+=(-s "$account" -i append)
jshon+=(-s "${SETH_BLOCK-latest}" -i append)
balance=$(seth --jsonrpc eth_getBalance "${jshon[@]}")
[[ $balance = 0x* ]] && balance=$(seth --to-dec "$balance")
eth=$(seth --to-fix 18 "$balance")
echo "$eth ETH"
