#!/usr/bin/env bash
### seth---abi-event-json -- print the JSON ABI for a single event
### Usage: seth --abi-event-json <sig>
set -e

if ! [[ $1 =~ ^([^\(]+)\(([^\(]*)\)$ ]]; then
  echo >&2 "${0##*/}: error: bad signature: $1"
  exit 1
fi

name=${BASH_REMATCH[1]}
input_types=${BASH_REMATCH[2]//,/ }

for type in $input_types; do
  inputs_jshon+=(-n {} -s "x$((++n))" -i name -s "$type" -i type -i append)
done

jshon <<<[] -n {} \
-s "$name" -i name -s event -i type \
-n [] "${inputs_jshon[@]}" -i inputs \
-i append
