#!/usr/bin/env bash
### seth-call -- call a contract without updating the blockchain
### Usage: seth call [-f <sender>] [-v <value>] <recv> [<data>]
###    or: seth call [-f <sender>] [-v <value>] <recv> <sig> [<args>]
###
### Perform a local call to <recv> (without creating a transaction).
### Print the result to standard output (decoded, if <sig> is given).
###
### With `-f <sender>', simulate calling <recv> from <sender>
### With `-v <value>', simulate transferring <value> to <recv>.
### With `-b <block>', use the state of the blockchain as of <block>.
###
### If <sig> has the form `<name>(<types>)', infer <data> from <sig>/<args>.
### If no <sig> or <data> is given, read it from standard input instead.

set -e
to=$(seth --to-address "${1?missing receiver}")
data=$(seth calldata ${2+"${@:2}"})
jshon+=(-n {})
jshon+=(-s "$data" -i data)
jshon+=(-s "$to" -i to)
jshon+=($(seth --send-params))
jshon+=(-i append)
[[ $SETH_BLOCK ]] && jshon+=(-s "$SETH_BLOCK" -i append)
result=$(seth --jsonrpc eth_call "${jshon[@]}")
seth --decode "$2" <<<"$result"
