#!/usr/bin/env bash
### seth---test-output -- execute a command and verify its output
### Usage: seth --test-output 10< <expected> <command> [<args>]
### Execute <command> and exit non-zero if it fails or its output is wrong.
###
### If <command> suceeeds, compare its output to <expected> (read from
### file descriptor 10 instead of 0 to avoid conflicts with <command>).
###
### If the output matches <expected>, print an `ok' message and exit zero.
set -e
tmpdir=$(mktemp -d)
cat <&10 >"$tmpdir/output.expected"

if "$@" &>"$tmpdir/output.actual"; then :; else
  echo "### Unexpected exit code ($?)"
fi

if ! diff=$(cd "$tmpdir"; diff -u output.{expected,actual}); then
  echo "### Unexpected output:"
  sed "s/^/# /" <<<"$diff"
  exit 1
fi
