#!/usr/bin/env bash
### seth-status -- display client and network status information

set -e
seth client >/dev/null

commands=(
  block
  blockchain
  client
  gas-price
  hashrate
  listening
  mining
  protocol
  peer-count
)

for command in ${commands[*]}; do
  value=`seth $command || echo -`
  printf "%-15s %s\n" "$command" "$value" &
done | LANG=C sort; wait
