#!/usr/bin/env node
var abi = JSON.parse(process.argv[2])
var { execFileSync } = require("child_process")
var call = (name, ...args) => execFileSync(name, args, { encoding: "utf-8" })

console.log(JSON.stringify(abi.filter(
  x => x.type == "event"
).map(event => {
  var sig = `${event.name}(${event.inputs.map(x => x.type).join(",")})`
  var hexdata = call("seth", "--from-ascii", sig).trim()
  var topic = call("seth", "keccak", hexdata).trim()
  return Object.assign(event, { topic })
}, null, 2)))
