#!/usr/bin/env bash
### Usage: seth --to-hexdata [<hexdata>]
set -e

if [[ $# = 0 ]]; then
  set -- "$(cat)"
elif [[ $# != 1 ]]; then
  seth --bad-usage "$0"
fi    

if [[ $1 = @* ]]; then
  value=$(seth --lookup "$1")
  "$0" "$value"
elif [[ $1 =~ ^0x[[:xdigit:]]*$ ]]; then
  echo "${1,,}"
elif [[ $1 =~ ^[[:xdigit:]]+$ ]]; then
  echo "0x${1,,}"
else
  seth --error "$0" "invalid hexdata: \`$1'"
fi
