#!/usr/bin/env bash
set -e
chain=$(seth chain)
name=${chain%%:*}_${1#@} name=${name^^} name=${name//-/_}

if [[ ${chain%%:*} = unknown ]]; then
  echo >&2 "${0##*/}: error: unknown chain: $chain"
  exit 1
elif ! [[ ${!name} ]]; then
  echo >&2 "${0##*/}: error: not found: \`$name'"
  exit 1
else
  echo "${!name}"
fi
