#!/bin/sh -e
if seth is-mining; then
  status="yes [`seth hashrate || echo unknown hashrate`]"
else
  status=no
fi

difficulty=`seth difficulty`
echo "$status [difficulty: $((difficulty / 1000000000)) trillion]"
