#!/usr/bin/env bash
set -e
data=$(cat)
url=${SETH_RPC_URL:-${SETH_RPC_HOST:-localhost}:${SETH_RPC_PORT:-8545}}
[[ $SETH_DEBUG_CURL ]] && set -x
echo "$(curl -sS -H "Content-Type: application/json" "$url" -d "$data")"
