#!/usr/bin/env bash
### seth-status -- display Ethereum client and network status information

set -e
seth client >/dev/null

commands=(
  block
  chain
  client
  gas-price
  hashrate
  listening
  mining
  protocol
  peers
)

for command in ${commands[*]}; do
  value=`seth $command || echo -`
  printf "%-15s %s\n" "$command" "$value" &
done | sort; wait
