#!/usr/bin/env bash
[[ $# = 1 ]] || seth --bad-usage "$0"
[[ $1 = *\ * ]] || set -- "$1 wei"
number=${1%% *} unit=${1#* }

case ${unit,,} in
  wei) scale=0;;
  gwei) scale=9;;
  eth) scale=18;;
  *) seth --error "$0" "unrecognized monetary value: \`$1'"
esac

bc <<<"$number * 10 ^ $scale / 1"
