#!/usr/bin/env bash
### seth-tx -- print general or specific information about a transaction
### Usage: seth tx <tx-hash> [<field>]
### Show information about the transaction <tx-hash>.
###
### If <field> is given, print only that piece of information.
### If no <field> is given, show all the fields in a big table.
set -e
[[ $# = [12] ]] || seth --bad-usage "$0"
tx=$(seth get-tx-by-hash "$1")
[[ $tx = null ]] && seth --error "$0" "no such transaction: $1"
[[ $2 ]] && exec seth --field "$2" <<<"$tx"
echo "$tx"
