#!/usr/bin/env bash
set -e
data=$(cat)
: ${ETH_RPC_URL:=${ETH_RPC_HOST:-localhost}:${ETH_RPC_PORT:-8545}}
[[ $SETH_DEBUG_CURL ]] && set -x
curl -sS -H "Content-Type: application/json" "$ETH_RPC_URL" -d "$data"
