#!/usr/bin/env bash
### seth-sign -- sign arbitrary data with one of your account keys
### Usage: seth sign [-F <sender>] <data>
### Sign <data> with the private key of <account>.
set -e
[[ $# = 1 ]] || seth --bad-usage "$0"
[[ $ETH_FROM ]] || seth --error "$0" "\`ETH_FROM' not set"
SENDER=$(seth --to-address "$ETH_FROM")
DATA=$(seth --to-hexdata "$1")
jshon+=(-s "$SENDER" -i append)
jshon+=(-s "$DATA" -i append)
seth --jsonrpc eth_sign "${jshon[@]}"
