#!/usr/bin/env node
var PROGRAM = process.argv[1].replace(/*\//, "")

if (!process.env.SETH_ABI) {
  console.error(`${PROGRAM}: error: please set \`SETH_ABI'`)
  process.exit(1)
}

var abi = JSON.parse(process.env.SETH_ABI)
var sig = ({ name, inputs }) => `${name}(${
  inputs.map(x => x.type).join(",")
})`

var events = abi.filter(
  x => x.type == "event"
).reduce((result, event) => Object.assign(result, {
  [keccak(sig(event))]: event,
}), {})

var event = JSON.parse(process.argv[2])
var type = abi[event.topics[0]]

if (type) {
  var i = 1, j = 0
  console.log({
    sig: sig(type),
    inputs: type.inputs.reduce((result, param) => Object.assign(result, {
      [param.name]: param.indexed ? event.topics[i++] : (
        event.data.replace(/^0x/, "").match(/.{64}/g)[j++]
      )
    }), {})
  })
}
