#!/usr/bin/env bash
set -e
[[ $SETH_FOLLOW ]] && {
  echo >&2 "${0##*/}: error: \`--follow' not supported"
  exit 1
}
params=(
  module=logs action=getLogs
  address="$1" fromBlock="$2" toBlock=latest
  apikey="$ETHERSCAN_API_KEY"
)
query=$(printf "&%s" "${params[@]}")
response=$(seth curl https://api.etherscan.io/api${query/&/?})
message=$(jshon <<<"$response" -e message -u)
result=$(jshon <<<"$response" -e result -j)
if [[ $message = OK || $result = "[]" ]]; then
  jshon <<<"$result" -a -j
else
  echo >&2 "${0##*/}: error: $response"
  exit 1
fi
