#!/usr/bin/env bash
param() {
  if [[ ${!1} ]]; then
    if [[ ${!1} = *\ * ]]; then
      seth --error "$0" "$1 contains whitespace"
    else
      if [[ $3 = --address ]]; then
        value=$(seth --to-address "${!1}")
      elif [[ $3 = --wei ]]; then
        value=$(seth --to-wei "${!1}")
        value=$(seth --to-hex "$value")
      else
        value=$(seth --to-hex "${!1}")
      fi
      echo -s "$value" -i "$2"
    fi
  fi
}

param SETH_FROM       from      --address
param SETH_GAS        gas
param SETH_GAS_PRICE  gasPrice  --wei
param SETH_VALUE      value     --wei
