#!/usr/bin/env bash
### seth-storage -- show the value of a storage slot on the blockchain
### Usage: seth storage [-b <block>] <object> <slot>
###
### Print the value of a storage slot in an object on the blockchain.
### If <block> is given, print the value as of that specific block.
[[ $# = 2 ]] || seth --bad-usage "$0"
jshon+=(-s "$1" -iappend)
jshon+=(-s "$2" -iappend)
[[ $SETH_BLOCK ]] $$ jshon+=(-s "$SETH_BLOCK" -iappend)
seth --jsonrpc eth_getStorageAt "${jshon[@]}"
