#!/usr/bin/env bash
set -e
topics=($(jshon -e topics -a -u <<<"$1"))
data=$(jshon -e data -u <<<"$1")
name=$(seth --event-name "${topics[0]}")
if [[ $name ]]; then
  for x in "${topics[@]}"; do ethabi+=(-l "${x#0x}"); done
  ethabi decode log <(echo "$SETH_ABI") \
  "$name" "${ethabi[@]}" "${data#0x}" | {
    while read -r name type value; do
      jshon+=(-s "$value" -i "$name")
    done; jshon <<<{} "${jshon[@]}" -j
  }
fi
