#!/usr/bin/env bash
set -e
tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT
kcov "$tmpdir" "${0%/*}/seth" "$@"
{ for x in ${0%/*}/*; do
    if ! [[ -L $x ]]; then
      echo 0.0; echo "$x"
    fi
  done
  { cat "$tmpdir/seth/index.json"
    echo 'console.log(JSON.stringify(data))'
  } | node | jshon -e files -a -e covered -u -p -e summary_name -u
} | while read -r covered; read -r file; do
  echo "$covered"; echo "${file##*/}"
done | paste -s -d '\t\n' |
sort -r -n | sort -u -k 2 | sort -n | sed 's/\..//' |
grep -v ^100 | grep -v '\.t$'
