#!/usr/bin/env bash
### seth-send-raw -- publish an already-signed transaction to the blockchain
### Usage: seth send-raw [<txdata>]
### Publish a previously signed transaction to the blockchain.
###
### If no <txdata> is given, read it from standard input instead.
set -e
txdata=$(seth --to-hexdata "$@")
jshon+=(-s "$txdata" -iappend)
seth --jsonrpc eth_sendRawTransaction "${jshon[@]}"
