#!/usr/bin/env bash
### seth-abi -- convert an ABI from Solidity syntax to JSON form
### Usage: seth abi <solidity-fragment>
set -e
[[ $1 ]] || seth --bad-usage "$0"
input="pragma solidity ^0.4.8; contract A { $1 }"
output=$(solc --combined-json=abi <<<"$input")
abi=$(jshon -e contracts -e A -e abi -u <<<"$output")
seth --decorate-abi "$abi"
