#!/usr/bin/env bash
set -e
### seth -- command-line Ethereum RPC client
### Usage: seth [<options>] <command> [<args>]
###    or: seth <command> --help
###
### Perform Ethereum RPC calls from the comfort of your command line.
###
### Connection options:
###
###    -h, --rpc-host=<host>      RPC endpoint host (default: `localhost')
###    -p, --rpc-port=<number>    RPC endpoint port (default: `8545')
###    -u, --rpc-url=<url>        RPC endpoint URL (overrides `-h' and `-p')
opts+=(h:p:u:)
optl+=(rpc-host:,rpc-port:,rpc-url:,)
###
### Transaction options:
###
###    -f, --from=<account>       account to use or send transaction from
###    -o, --origin=<account>     synonym for `--from'
###
###    -g, --gas=<number>         number of units of gas to provide
###        --gas-price=<money>    price of each gas unit (e.g. `20 Gwei')
###    -v, --value=<money>        amount of money to send (e.g. `0.1 ETH')
opts+=(f:o:g:v:)
optl+=(from:,origin:,gas:,gas-price:,value:)
###
### Options for seth-send(1) and seth-receipt(1):
###
###    -a, --async                exit after printing transaction hash
opts+=(a)
optl+=(async)
###
### Options for seth-call(1), seth-estimate(1) and others:
###
###    -b, --block=<number>       block number (default: `latest')
opts+=(b:)
optl+=(block:,)
###
### Other options:
###
###    -s, --silent               suppress standard error logging output
###    -q, --quiet                synonym for `--silent'
opts+=(sq)
optl+=(silent,quiet)

if ! [[ $SETH_INITIALIZED ]]; then
  export SETH_INITIALIZED=true
  [[ -e ~/.sethrc ]] && . ~/.sethrc
fi

if [[ $2 = --help ]]; then
  seth help -- "$1"
elif [[ $1 = -* ]] && which "seth-$1" &>/dev/null; then
  seth-"$@"
else
  args=$(getopt -n ${0##*/} -o "${opts[*]}" -l "${optl[*]}" -- "$@")
  eval set -- $args

  while [[ $1 ]]; do
    case $1 in
      --)              shift; break;;

      -h|--rpc-host)   shift; export SETH_RPC_HOST=$1;;
      -p|--rpc-port)   shift; export SETH_RPC_PORT=$1;;
      -u|--rpc-url)    shift; export SETH_RPC_URL=$1;;


      -o|--origin)     shift; export SETH_FROM=$1;;
      -f|--from)       shift; export SETH_FROM=$1;;

      -g|--gas)        shift; export SETH_GAS=$1;;
         --gas-price)  shift; export SETH_GAS_PRICE;;
      -v|--value)      shift; export SETH_VALUE=$1;;

      -a|--async)      export SETH_ASYNC=true;;

      -b|--block)      shift; export SETH_BLOCK=$1;;

      -s|--silent)     export SETH_SILENT=true;;
      -q|--quiet)      export SETH_SILENT=true;;

      *)
        printf "${0##*/}: internal error: %q\n" "$1"
        exit 1
    esac
    shift
  done

  export SETH_ORIGIN=${SETH_ORIGIN-${SETH_FROM-$ETH_FROM}}

  exec "seth-${1-help}" "${@:2}"
fi
