#!/usr/bin/env bash
### seth---decode -- extract return values from hexdata
### Usage: echo <hexdata> | seth --decode [<name>(<inputs>)(<outputs>)]

set -e
data=`cat`
if [[ $1 =~ ^([^[\(]+)[\([].*[\([] ]]; then
  name=${BASH_REMATCH[1]}
  abi=`seth --abi-json "$1"`
  result=$(ethabi decode function <(echo "$abi") "$name" "${data#0x}")
  if [[ $result = error* ]]; then
    echo >&2 "ethabi: $result"
    exit 1
  else
    cut -d' ' -f2 <<<"$result"
  fi
else
  echo "$data"
fi
