#!/usr/bin/env bash
set -e
dapp --sanity "$0"
[[ ${1?missing package name} = */* ]] || set -- "dapphub/$1"
(set -x; git submodule add --force "https://github.com/$1" "lib/${1#*/}")
(set -x; git submodule update --init --recursive)
dapp --commit "$0" "$@"
