#!/usr/bin/env bash
set -e
for x; do
  if [[ $x =~ [^/]+/([^/]+) ]]; then
    echo "$x" "${BASH_REMATCH[1]}" "https://github.com/$x"
  elif [[ $x =~ .*[@:/](.*) ]]; then
    echo "$x" "${BASH_REMATCH[1]%.*}" "$x"
  else
    echo "$x" "$x" "https://github.com/dapphub/$x"
  fi
done
