#!/usr/bin/env bash
set -o noclobber
mk() { cat >$1; (set -x; git add $1); }
name=$(basename $(pwd))
(set -x; git init)
(set -x; mkdir -p lib src)
mk .gitignore <<.
/build
.
mk Makefile <<.
all:; dapp make
test:; dapp test
.
mk src/Makefile <<.
all:; \$(MAKE) -C ..
.
mk ERC190.json <<.
{
  "package_name": "$name",
  "version": "0.1.0",
  "meta": {
    "description": "",
    "license": "",
    "authors": [
    ],
    "keywords": [
    ]
  },
  "dependencies": {
  },
  "deployments": {
  }
}
.
dapp --save "$0" "$name"
echo OK.
