#!/usr/bin/env bash
set -e
shopt -s globstar

sender=0x00a329c0648769a73afac7f9381e08fb43dbea72
nonce=1048576

libraries=($(dapp --find-libraries))

for lib in "${libraries[@]}"; do
  address=$(dapp address "$sender" "$nonce")
  links+=" $lib:$address"
  ((nonce++))
done

(set -x; solc --link --libraries "$links" "${DAPP_OUT?}"/**/*.bin)

# pass the library bin files through to ethrun
# (needs to be exact same order as above for nonces)
function binfile() { sed -E "s/.*:(.*)/$DAPP_OUT\/\1.bin/"; }
deploy=($(printf "%s\n" "${libraries[@]}" | binfile))

(set -x; dapp quicktest "$@" "$DAPP_OUT" "${deploy[@]}")
