#!/usr/bin/env bash
set -o noclobber
mk() { cat >"$1"; (set -x; git add "$1"); }
mka() { cat >>"$1"; (set -x; git add "$1"); }
name=$(basename "$(pwd)")
(set -x; git init)
(set -x; mkdir -p lib src)
mka .gitignore <<.
/out
.
mk Makefile <<.
all:; dapp build
test:; dapp test
.
mk Dappfile <<.
name            $name
description
version         0.0.1

author          $(whoami)
license         Apache-2.0
.
mk src/test.sol <<.
pragma solidity ^0.4.8;

import "ds-test/test.sol";

contract Test is DSTest {
    function test_basic_sanity() {
        assert(true);
    }

    function testFail_basic_sanity() {
        assert(false);
    }
}
.
git add -A
dapp --commit "$0" "$name"
(set -x; dapp install ds-test)
(set -x; make test)
