#!/usr/bin/env bash
set -ex; tmp=$(mktemp -d); cd "$tmp"

# Try initializing and testing a new dapp
( mkdir foo; cd foo; dapp init )

# Try testing a bunch of dappsys packages
dappsys() {
  git clone https://github.com/dapphub/"$1" --recursive
  ( cd "$1" && dapp test )
}
dappsys ds-auth
dappsys ds-exec
dappsys ds-guard
dappsys ds-math
dappsys ds-roles
# dappsys ds-cache
# dappsys ds-multisig
# dappsys ds-token
# dappsys ds-value
# dappsys ds-vault
