#!/usr/bin/env bash
set -e

if [ "$DAPP_VERBOSE" ]; then set -x; fi

state=$(dapp --make-library-state)
function clean() { rm -rf "$state"; }
trap clean EXIT

find "${DAPP_OUT?}" -type f -name '*.sol.json' -print0 |
  xargs -0 -n1 -I{} hevm dapp-test --json-file={} --dapp-root=. --state="$state"
