#!/usr/bin/env bash
set -e

gethdir=$HOME/.dapp/testnet
chainid=2000
while true; do
  if [[ ! -d "$gethdir/$chainid" ]]; then break; fi
  chainid=$((chainid + 1))
done

chaindir="$gethdir/$chainid"
port=$((chainid + 30000))

mkdir -p "$chaindir/config"

function clean() { ( echo; set -x; rm -rf "$chaindir" ); }
trap clean EXIT

address=$(
  geth 2>/dev/null account new --datadir "$chaindir" --password=<(exit) 2>/dev/null \
    | grep Address | sed 's/Address: {\(.*\)}/\1/')

echo >&2 "dapp-testnet:   Account: $address"
echo >&2 "dapp-testnet:   RPC URL: http://127.0.0.1:$chainid"
echo >&2 "dapp-testnet:  TCP port: $port"
echo >&2 "dapp-testnet:  Chain ID: $chainid"
echo >&2 "dapp-testnet:  Database: $chaindir"
echo >&2 "dapp-testnet:  Geth log: $chaindir/geth.log"

echo "$address"                  > "$chaindir/config/account"
echo "http://127.0.0.1:$chainid" > "$chaindir/config/rpc-url"
echo "$port"                     > "$chaindir/config/node-port"

geth \
  2> >(tee "$chaindir/geth.log" | grep --line-buffered Success | sed 's/^/geth: /' >&2) \
  --datadir "$chaindir" --dev --dev.period "$DAPP_PERIOD" --networkid "$chainid" --port="$port" \
  --rpc --rpcapi "web3,eth,debug" --rpccorsdomain '*' --nodiscover \
  --rpcport="$chainid" --unlock="$address" --password=<(exit)
