#!/usr/bin/env bash
set -e
(set -x; dapp clean)

opts=($SOLC_FLAGS)
json_opts=--combined-json=abi,bin,bin-runtime,srcmap,srcmap-runtime
solc --help | grep -q -- --overwrite && opts+=(--overwrite)

remappings=$(dapp remappings)
if [[ $remappings ]]; then
  while read -r line; do opts+=("$line"); done <<<"$remappings"
fi

shopt -s nullglob
for x in "${DAPP_SRC}"/*.sol; do
  (set -x; solc "${opts[@]}" --abi --bin --bin-runtime = -o "$DAPP_OUT" "$x")
  json_file=$DAPP_OUT/${x#$DAPP_SRC}.json
  (set -x; solc "${opts[@]}" "${json_opts[@]}" = "$x" >"$json_file")
done
