#!/usr/bin/env bash
set -e
(set -x; dapp clean)
version=$(sed 's/.*\.4\.\([0-9]*\).*/\1/'<<<`solc --version`)
if [ $version -ge "10" ]; then
  export SOLC_FLAGS="--overwrite $SOLC_FLAGS"
fi
solc=(solc $SOLC_FLAGS --abi --bin --bin-runtime = -o "$DAPP_OUT")
remappings=$(dapp remappings)
while read -r line; do solc+=("$line"); done <<<"$remappings"
shopt -s nullglob
for x in $DAPP_SRC/*.sol; do (set -x; "${solc[@]}" "$x"); done
