#!/usr/bin/env bash
set -e -o pipefail
solc=(solc $SOLC_FLAGS --abi --bin --bin-runtime = -o "$DAPP_OUT" --overwrite)
remappings=$(dapp remappings)
while read -r line; do solc+=("$line"); done <<<"$remappings"
shopt -s nullglob
for x in $DAPP_SRC/*.sol; do (set -x; "${solc[@]}" "$x"); done
