#!/usr/bin/env bash
set -o noclobber
mk() { cat >$1; (set -x; git add $1); }
name=$(basename $(pwd))
(set -x; git init)
(set -x; mkdir -p lib src)
mk .gitignore <<.
/src.out
.
mk Makefile <<.
all  :; dapp make
test :; dapp test
.
mk src/Makefile <<.
all :; \$(MAKE) -C ..
.
mk Dappfile <<.
name            $name
description
version         0.0.1

author          $(whoami)
license         Apache-2.0
.
dapp --save "$0" "$name"
echo OK.
