#!/usr/bin/env bash
file=`dirname $0`/seth${1+-$1}
header=$(grep -oP '^(\S)\1\1( \K.*)?' "$file" | perl -pe 's/^(\S)\1\1$//')

if ! [[ $header ]]; then
  echo "${0##*/}: no help for \`seth-$1'"
  sed "s/^/> /" "$file"
elif [[ `wc -l <<<"$header"` = 1 ]]; then
  echo "$header"
else
  sed 1d <<<"$header"
fi

if ! [[ $1 ]]; then
  for file in `dirname $0`/seth-*; do
    if ! [[ -L $file ]]; then
      programs+=("$file")
    fi
  done

  cat <<.

Commands:

$(grep -hoP "^(\\S)\\1\\1 seth-\\K[^ ]* -- .*" "${programs[@]}" |
  sed "s/ -- / /" | while read name label; do
    printf "   %-12s  %s\n" "$name" "$label"
  done)

Report bugs to <https://github.com/dbrock/seth>.
.
fi
