#!/usr/bin/env bash
### seth-call -- call a contract without updating the blockchain
### Usage: seth call [-f <account>] [-v <value>] <receiver> [<calldata>]
### Perform a local call to <receiver> without creating a transaction.
###
### With `-f <account>', simulate calling <receiver> from <account>
### With `-v <value>', simulate transferring <value> to <receiver>.
### With `-b <block>', use the state of the blockchain as of <block>.
###
### If no <calldata> is given, read it from standard input instead.

set -e
receiver=`seth --to-hexdata "${1?missing receiver}"`
calldata=`seth --to-hexdata ${2+"$2"}`
seth --jsonrpc eth_call \
  -n {} \
    -s $receiver -i to \
    -s $calldata -i data \
    `seth --send-params` \
    -iappend \
  ${SETH_BLOCK+
  -s "$SETH_BLOCK"
    -iappend}
