#!/usr/bin/env bash
### token -- command-line client for Ethereum tokens (ERC20)
### Usage: token [<options>] <command> [<args>]
###    or: token <command> --help
###
### Perform ERC20 token errands from the comfort of your command line.

set -e

if [[ $2 = --help ]]; then
  token-help "$1"
elif [[ $2 = --usage ]]; then
  token-help "$1" >&2
  exit 1
else
  token-"${1-help}" "${@:2}"
fi
