#!/bin/sh -e
### token-allowance -- print the amount one account can spend from another
### Usage: token allowance <token> <owner> <spender>
[ $# = 3 ] || token allowance --usage
sig="allowance(address,address)(uint)"
allowance=$(seth call "$1" "$sig" "$2" "$3")
token --format "$1" "$allowance"
