#!/bin/sh -e
### token-transfer -- transfer tokens from one account to another
### Usage: token transfer <token> [<source>] <recipient> <amount>
### Note: <amount> must be an integer representing wei (or equivalent).
if [ $# = 3 ]; then
  amount=$(token --parse "$3")
  sig="transfer(address,uint)(bool)"
  seth send "$1" "$sig" "$2" "$amount"
elif [ $# = 4 ]; then
  amount=$(token --parse "$4")
  sig="transferFrom(address,address,uint)(bool)"
  seth send "$1" "$sig" "$2" "$3" "$amount"
else
  token transfer --usage
fi
