#!/usr/bin/env bash
### token -- command-line client for Ethereum tokens (ERC20)
### Usage: token [<options>] <command> [<args>]
###    or: token <command> --help
###
### Easily do things with your Ethereum tokens.
set -e
[[ $2 = --help  ]] && exec token-help "$1"
[[ $2 = --usage ]] && { token-help "$1" >&2; exit 1; }
token-"${1-help}" "${@:2}"
