resolver: lts-16.10
packages:
  - .
extra-deps:
  - HSH-2.1.3
  - monoidal-containers-0.6.0.1
  - restless-git-0.7
  - s-cargot-0.1.4.0
  - semver-range-0.2.8
  - text-format-0.3.2
  - these-1.0.1
  - tree-view-0.5
  - witherable-0.3.5
  - witherable-class-0
  - github: LeventErkok/sbv
    commit: f913d4e002e1f76a12184677d315774943747eed
  #- config-ini-0.2.4.0
  #- data-clist-0.1.2.2
  #- free-5.1.2
  #- ghci-pretty-0.0.2
  #- HSH-2.1.3
  #- ipprint-0.6
  #- megaparsec-7.0.5
  #- multiset-0.3.4.1
  #- QuickCheck-2.12.6.1
  #- restless-git-0.7
  #- rosezipper-0.2
  #- s-cargot-0.1.4.0
  #- sr-extra-1.46.3.2
  #- tree-view-0.5
  #- text-format-0.3.2
  #- text-zipper-0.10.1
  #- Unixutils-1.54.1
  #- vty-5.25.1
  #- word-wrap-0.4.1
flags: {}
extra-package-dbs: []
