resolver: lts-16.11
packages:
- .
extra-deps:
- Decimal-0.5.1
- ghci-pretty-0.0.2
- HSH-2.1.3
- ipprint-0.6
- monoidal-containers-0.6.0.1
- restless-git-0.7
- s-cargot-0.1.4.0
- sr-extra-1.46.3.2
- these-1.0.1 # latest is 1.1.1.1, but monoidal-containers-0.6.0.1 requires <1.1
- tree-view-0.5
- text-format-0.3.2
- Unixutils-1.54.1
- witherable-0.3.5
- cryptonite-0.28@sha256:b6c75e62b4c655d4cb1bcbb80d01430d136aac32bd6962c86c84738935cc8f9d,18195
- github: dmjio/semver-range
  commit: d8d9db892ddb6ae267c9bcbc4f6602668433f12a
- github: leventerkok/sbv # 8.9
  commit: b64905e2698c320ac14ffbad53325d33081839fb
flags: {}
extra-package-dbs: []
image:
  container:
    name: mbrock/hevm
    base: haskell:8.0.1
