#!/usr/bin/env bash
### seth---max-uint -- print the maximum uint of the given bits
### Usage: seth --max-uint [<bits>]
set -e
[[ $1 ]] && bits=$1 || bits=256
echo "0x$(bc <<< "obase=16; 2^$bits - 1" | tr A-F a-f)"
