#!/usr/bin/env bash
### seth-abi-encode -- ABI encode values, and prints the encoded values without the function signature
### Usage: seth abi-encode <sig> [<args>]
###
### ABI encode values based on a provided function signature, slice off the leading the function signature,
### and print the result. It does not matter what the name of the function is, as only the types and values
### affect the output.

set -e

x=$(seth calldata $@); # generate full calldata based on function signature
echo "0x${x:10}" # slice off the function signature and only keep the encoded values
