#!/usr/bin/env bash
# seth-keccak -- print the Keccak hash of an arbitrary piece of data
set -e
[[ $# = 1 ]] || seth --fail-usage "$0"
hexdata=$(seth --to-hexdata "$1")
seth rpc web3_sha3 -- -s "$hexdata" -i append
