#!/usr/bin/env bash
### seth---to-address -- convert hex into checksummed address
### Usage: seth --to-address <hex>
set -e
[[ $1 ]] || set -- "$(cat)"
hexdata=$(seth --to-hexdata "$@")
[[ ${#hexdata} = 42 ]] ||
seth --fail "${0##*/}: error: bad address: \`$hexdata'"
seth --to-checksum-address "$hexdata"
