#!/usr/bin/env bash
set -e

show-json() {
  if [[ $1 = \"*\" ]]; then
    unquoted=$(jshon <<<"[$1]" -a -u)
    echo "$unquoted"
  else
    echo "$1"
  fi
}

if [[ $SETH_JSON ]]; then
  jshon
else
  json=$(cat)
  case $json in
  \[*\]) jshon <<<"$json" -a -j |
    while read -r item; do
      show-json "$item"
    done;;
  \{*\}) jshon <<<"$json" -k |
    while read -r key; do
      value=$(jshon <<<"$json" -e "$key" -j)
      value=$(show-json "$value")
      printf "%-${SETH_KEY_WIDTH-23}s %s\\n" "$key" "$value"
    done | sort;;
  \"*\") show-json "$json";;
  *) echo "$json";;
  esac
fi
