#!/usr/bin/env bash
### seth-lookup-address -- returns the ENS name the provided address reverse resolves to
### Usage: seth lookup-address <name>
###
### Print the ENS name the provided address reverse resolves to. If the name is
### not owned or does not have a resolver configured, an `invalid data for
### function output` error will be thrown. An error will also be thrown
### if the forward and reverse resolution do not match.

set -e
shopt -s extglob
[[ $# -lt 2 ]] || seth --fail-usage "$0"

# verify chain ID
chainid=$(seth chain-id)
if [[ $chainid != @(1|3|4|5) ]]; then
  seth --fail "${0##*/}: error: using chain ID $chainid, but ENS lookups are only supported for chain IDs 1, 3, 4, and 5"
fi

# get namehash for <address>.addr.reverse
addressin=$(seth --to-hexdata $1) # make address lowercase
namein=$(echo $addressin.addr.reverse | cut -c3-)
namehash=0x$(seth namehash $namein | cut -c3-)

# get name from the resolver
ENS_REGISTRY=${SETH_ENS_REGISTRY:-'0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e'} # same on all supported networks
resolver=$(seth call $ENS_REGISTRY "resolver(bytes32)(address)" $namehash)
name=$(seth call $resolver "name(bytes32)(string)" $namehash)

# check the reverse direction and make sure the addresses match
address=$(seth resolve-name $name)
if [[ $(seth --to-hexdata $address) != $addressin ]]; then
  seth --fail "${0##*/}: error: forward resolution of the found ENS name $name did not match"
fi

# success
echo $name
