#!/usr/bin/env bash
### seth---to-dec -- convert hex into decimal
### Usage: seth --to-dec <hex>
set -e
[[ $1 ]] || exec xargs -n1 "$0"
hexdata=$(seth --to-hexdata "$1")
hexnum=${hexdata#0x}
num=$(bc <<<"ibase=16; $(tr a-f A-F <<<"$hexnum")")
# shellcheck disable=SC1003
tr -d '\n\\' <<<"$num"
echo
