#!/usr/bin/env bash
set -e
[[ $SETH_FOLLOW ]] && {
  echo >&2 "${0##*/}: error: \`--follow' not supported"
  exit 1
}
params=(
  "module=logs" "action=getLogs"
  "address=$1" "fromBlock=$2" "toBlock=latest"
  "apikey=$ETHERSCAN_API_KEY"
)
[[ "$3" ]] && params[6]="topic0=$3"
[[ "$4" ]] && params[7]="topic0_1_opr=and"
[[ "$4" ]] && params[8]="topic1=$4"
query=$(printf "&%s" "${params[@]}")
response=$(seth curl "${ETHERSCAN_API_URL?}""${query/&/?}")
message=$(jshon <<<"$response" -e message -u)
result=$(jshon <<<"$response" -e result -j)
if [[ $message = OK || $result = "[]" ]]; then
  jshon <<<"$result" -a -j
else
  echo >&2 "${0##*/}: error: $response"
  exit 1
fi
