#!/usr/bin/env bash
### seth-source -- fetch the contract source from etherscan
### Usage: seth source <address> [<options>]
###
### Requires an etherscan api key
set -e
[[ $ETHERSCAN_API_KEY ]] || {
  cat >&2 <<.

  You need an Etherscan Api Key to source contracts.
  Create one at https://etherscan.io/myapikey

  Then export it with \`export ETHERSCAN_API_KEY=xxxxxxxx'

.
  exit 1
}

ADDR=$(seth --to-address "$1")

chain=$(seth chain)

case "$chain" in
  ethlive|mainnet)
    URL="${ETHERSCAN_API_URL:-https://api.etherscan.io}"
    ;;
  ropsten|kovan|rinkeby|goerli)
    URL="${ETHERSCAN_API_URL:-https://api-$chain.etherscan.io}"
    ;;
  *)
    echo >&2 "Source fetching only works on mainnet, ropsten, kovan, rinkeby, and goerli."
    exit 1
esac


RESPONSE=$(seth curl "${URL}/api?module=contract&action=getsourcecode&address=${ADDR}&apikey=${ETHERSCAN_API_KEY}" | seth --show-json)

MSG=$(echo "$RESPONSE" | seth --field message)

ABI=$(echo "$RESPONSE" | seth --field result | jq '.[0].ABI' | seth --show-json)

[[ $MSG == OK ]] || seth --fail "error: bad response: $MSG"


if [[ $ABI == "Contract source code not verified" ]]; then
    seth --fail "$ABI"
else
    echo "$RESPONSE" | seth --field result | jq '.[0]'
fi
