#!/usr/bin/env bash
### seth-abi -- Generate ABI json for a given signature
### Usage: seth abi <signature>
### Example: seth abi "f(uint x)"
### Returns: {
###            "type": "function",
###            "name": "f",
###            "stateMutability": "nonpayable",
###            "inputs": [
###              {
###                "type": "uint256",
###                "name": "x"
###              }
###            ],
###            "outputs": []
###          }
### Example: seth abi "function f(bool, MyStruct(uint, bytes[][2])) returns (string)"
### Example: seth abi "event Event(uint32 x, bool indexed b)
### Example: seth abi "error SomeError(string msg)"

set -e
[[ $# = 1 ]] || seth --fail-usage "$0"

hevm abi --abi "$1"
