#!/usr/bin/env bash
### seth---calldata-decode -- extract calldata values from hexdata
### Usage: seth --calldata-decode <name>(<in-types>)(<out-types) <hexdata>
###
### Decode <hexdata> according to <in-types> (<out-types> are ignored).
hevm abidecode --abi "$1" --calldata "$2"
