#!/usr/bin/env bash
cat <<.
seth 0.8.2
Copyright (C) 2016, 2017  Daniel Brockman <daniel@dapphub.com>
License: GNU GPL version 3 or later <https://gnu.org/licenses/gpl>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.
