#!/usr/bin/env bash

set -e

jshon+=(-n {})
[[ $TO ]] && jshon+=(-s "$TO" -i to)
jshon+=(-s "$data" -i data)
# shellcheck disable=SC2207
jshon+=($(SETH_PARAMS_NO_GAS=1 seth --send-params))
jshon+=(-i append)

seth rpc eth_estimateGas -- "${jshon[@]}"