#!/usr/bin/env node
const usage = "Usage: seth calldata <sig> [<args>]>\n   or: seth calldata <file>\n   or: seth calldata <data>"
if (process.argv.length >= 3 &&
    process.argv[2].indexOf('(') >= 0) {
  // silence warnings we don't care about
  const log = console.log
  console.log = () => {};
  const ethers = require("./ethers.min.js");
  console.log = log;
  const sig = process.argv[2];
  try {
    const funcs = new ethers.utils.Interface(["function " + sig.replace(')(', ') returns (')]).functions;
      console.log(funcs[Object.keys(funcs)[0]].encode(process.argv.slice(3)))
    } catch (e) {
      console.error(e.toString())
      process.exit(1)
    }
} else if (process.argv.length == 3) {
  const {execFileSync}   = require('child_process');
  try {
    const yes = execFileSync("seth",
                             ["--to-hexdata",
                              process.argv[2]]
                            ).toString().replace('\n','')
    console.log(yes)
  } catch(e) {
    console.error(e)
    process.exit(1)
  }
} else {
  console.error(usage)
  process.exit(1)
}
