#!/usr/bin/env bash
set -e
name=${ETH_ENV+${ETH_ENV}_}${1#@}
name=$(tr "[:lower:]" "[:upper:]" <<<"$name")
name=${name//-/_}
[[ ${!name} ]] || seth --fail "${0##*/}: error: not found: \`$name'"
echo "${!name}"
