#!/usr/bin/env bash
set -e

function usage() {
  echo >&2 "Usage: seth --use <spec> <subcommand>..."
  echo >&2 "Example:"
  echo >&2
  echo >&2 "  $ seth --use solc:0.4.11 combined-json"
  echo >&2
  exit 1
}

[[ "$#" -gt 0 ]] || usage

query() {
  nix-env -q --installed --out-path --no-name "$1" 2>/dev/null
}

shopt -s extglob
case $1 in
  # package spec e.g. solc:0.4.12
  solc:[0-9].+([0-9.]))
    solc="solc-${1#solc:}"
    if store_path=$(query "solc-${1#solc:}"); then
      bin="$store_path/bin/solc"
    elif store_path=$(query "solc-static-${1#solc:}"); then
      bin="$store_path/bin/$solc"
    else
      bin=""
    fi
    ;;
  # some other solc binary name
  solc*)
    solc="$1"
    set +e
    bin="$(type -p "$solc")"
    ;;
  # if there's a '/', interpret as a path
  */*)
    bin="$1"
    ;;
  *)
    echo >&2 "${0##*/}: unrecognized package spec: $1"
    exit 1
esac
shift

[[ "$#" -gt 0 ]] || usage

if [[ -z "$bin" ]]; then
  echo >&2 "${0##*/}: Could not find ${solc} in your path or nix store."
  echo >&2 "Temporarily installing ${solc}..."
  echo >&2 "Tip: run \`nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.${solc//[-.]/_}\` for a lasting installation of this version."
  seth --nix-run "seth.override {solc = pkgs.runCommand \"solc\" { } \"mkdir -p \$out/bin; ln -s \${solc-static-versions.${solc//[-.]/_}}/bin/${solc} \$out/bin/solc\";}" seth "$@"

else
  set -e
  SOLCBIN="$(realpath -e "${bin}")"
fi

DAPP_SOLC="$SOLCBIN" seth "$@"
