#!/usr/bin/env bash
set -e

version=$(jshon --version)
min=20131105
if [[ $version -lt $min ]]; then
  echo >&2 "${0##*/}: error: jshon $version is too old (need $min or newer)"
  exit 1
fi

rpc-result() { jshon -Q -e result -j; }
rpc-error() { jshon -Q -e error -j; }

request=$(seth rpc-request -- "$@")
response=$(seth rpc-curl <<<"$request")
[[ $SETH_VERBOSE ]] && SETH_KEY_WIDTH=10 seth --show-json <<< "$request" | sed >&2 "s/^/${0##*/}:   /"

if result=$(rpc-result <<<"$response"); then
  seth --show-json <<<"$result"
elif error=$(rpc-error <<<"$response"); then
  { echo "$request"
    SETH_KEY_WIDTH=10 seth --show-json <<<"$error" | sed 's/^/error:   /'
  } | sed >&2 "s/^/${0##*/}: /"
  exit 1
else
  echo >&2 "$response"
  exit 1
fi
