#!/usr/bin/env bash
### seth-solc -- compile a single file using a default --standard-json input
### Usage: seth solc <source-file>
###
### The following environment variables can be set:
###   - DAPP_SOLC (default `solc`)
###   - DAPP_SOLC_OPTIMIZE (default false)
###   - DAPP_SOLC_OPTIMIZE_RUNS (default 200)
###
set -e

OPTIMIZE=${DAPP_SOLC_OPTIMIZE:-false}
RUNS=${DAPP_SOLC_OPTIMIZE_RUNS:-200}
SOLC=${DAPP_SOLC:-solc}

JSON="$(jq -n '{}
  | .language = "Solidity"
  | .sources[$src]["urls"] = [$src]
  | .settings.outputSelection["*"]["*"]=[
      "evm.bytecode",
      "abi",
      "storageLayout",
      "evm.bytecode.sourceMap",
      "evm.bytecode.linkReferences",
      "evm.bytecode.generatedSources",
      "evm.deployedBytecode.sourceMap",
      "evm.deployedBytecode.linkReferences",
      "evm.deployedBytecode.generatedSources"
    ]
  | .settings.outputSelection["*"][""] = ["ast"]
  | .settings.optimizer =
      if $optimize then {"enabled": $optimize, "runs": $runs}
      else {"enabled": $optimize}
      end
  ' --arg src "$1" --argjson optimize "$OPTIMIZE" --argjson runs "$RUNS")"

( [[ $SETH_VERBOSE ]] && set -x;
  echo "$JSON" | $SOLC --standard-json --allow-paths "$(realpath $1)" | jq . )
