#!/usr/bin/env bash
### seth-mktx -- construct a signed transaction using ethsign
### Usage: seth mktx [<opts>] [-F <from>] <to> <sig> [<args>]
###    or: seth mktx [<opts>] [-F <from>] <to> <calldata>
set -e

# shellcheck disable=SC2015
[[ $# ]] && [[ $ETH_FROM ]] || seth --fail-usage "$0"

value=$(seth --to-wei "${ETH_VALUE:-0}")
value=$(seth --to-hex "$value")
if [[ $2 ]]; then
  data=$(seth calldata "${@:2}")
fi

args=(
  --from "$(seth --to-address "$ETH_FROM")"
  --nonce "${ETH_NONCE:-$(seth nonce "$ETH_FROM")}"
  --chain-id "$(seth chain-id)"
  --gas-limit "${ETH_GAS:-200000}"
  --value "$value"
  --data "${data:-0x}"
)

if [[ $SETH_CREATE ]]; then
  args+=(--create)
else
  args+=(--to "$(seth --to-address "$1")")
fi

if [[ $ETH_GAS_PRICE ]]; then
  args+=(--gas-price "$ETH_GAS_PRICE")
elif [[ $ETH_PRIO_FEE ]] && [[ $ETH_MAX_FEE ]]; then
  args+=(--prio-fee "$ETH_PRIO_FEE")
  args+=(--max-fee "$ETH_MAX_FEE")
else
  echo >&2 "required: gas price or (max prio and max fee)"         
  seth --fail-usage "$0"
fi


   
if [ -n "$ETH_PASSWORD" ]; then args+=(--passphrase-file "$ETH_PASSWORD"); fi

tx=$([[ $SETH_VERBOSE ]] && set -x; ethsign tx "${args[@]}")
echo "$tx"
