#!/usr/bin/env bash
### seth-run-tx -- execute a transaction using hevm
### Usage: seth run-tx <tx-hash> [<options>]
### or:    seth run-tx <tx-info> [<options>]
###
### Run a transaction with hevm in the environment of the given transaction.
###
### Attempts to fetch contract source from etherscan if `ETHERSCAN_API_KEY` is set.
###
### With `--state dir`, load and save state from `dir`
### With `--trace`, print the call trace of the transaction.
### With `--debug`, execute with hevm's interactive debugger
### With `--no-src`, do not attempt to fetch contract source from etherscan
### With `--source`, manually supply a solc compiler output json (implies --no-src)
set -e

# if the argument begins with 0x, we assume it to be a tx hash
# otherwise, we assume that it contains the result of a seth tx call
if [[ $1 = 0x* ]]; then
  tx=$(seth tx "$1")
elif [[ $1 = blockHash* ]]; then
  tx=$1
else
  seth --fail "${0##*/}: malformed transaction hash or data: $1"
fi

TO=$(<<< "$tx" seth --field to)
DATA=$(<<< "$tx" seth --field input | seth --to-hex)
if [[ "$TO" == 'null' ]]; then
  opts+=(--create --code "$DATA")
else
  opts+=(--address "$TO" --calldata "$DATA")
fi

if [[ -n "$ETHERSCAN_API_KEY" && -z "$DAPP_JSON"  && "$SETH_NOSRC" != yes ]]; then
    TMP=$(mktemp -d)
    DAPP_JSON="$TMP/solc.out.json"
    seth bundle-source --dir "$TMP" "$TO" > "$DAPP_JSON" || :
fi

opts+=(--caller "$(<<< "$tx" seth --field from)" )
opts+=(--origin "$(<<< "$tx" seth --field from)")
opts+=(--value  "$(<<< "$tx" seth --field value)")
opts+=(--gas    "$(<<< "$tx" seth --field gas)")
opts+=(--nonce  "$(<<< "$tx" seth --field nonce)")
opts+=(--number "$(<<< "$tx" seth --field blockNumber)")
opts+=(--block  "$(("$(<<< "$tx" seth --field blockNumber)" - 1))")
opts+=(--rpc    "${ETH_RPC_URL}")
opts+=(--timestamp "${HEVM_TIMESTAMP:-$(seth block "$(<<< "$tx" seth --field blockNumber)" timestamp)}")
opts+=(--chainid   "${ETH_CHAINID:-$(seth rpc eth_chainId | seth --to-dec)}")

[[ "$HEVM_STATE" ]] && opts+=(--state "$HEVM_STATE")
[[ "$HEVM_DEBUG" ]] && opts+=(--debug)
[[ "$HEVM_TRACE" ]] && opts+=(--trace)
[[ "$DAPP_JSON" ]]  && opts+=(--json-file "$DAPP_JSON")

([[ $SETH_VERBOSE ]] && set -x; [[ $DAPP_JSON ]] && cd "$TMP"; hevm exec "${opts[@]}")
