#!/usr/bin/env node
if (!process.env.SETH_ABI) {
  console.error("seth---event-name: error: `SETH_ABI' not set")
  process.exit(1)
}

var topic = process.argv[2]
var abi = JSON.parse(process.env.SETH_ABI)
var event = abi.filter(x => x.topic == topic)[0]

if (event) {
  console.log(event.name)
}
