#!/usr/bin/env bash
### seth-abi -- convert an ABI from Solidity syntax to JSON form
### Usage: seth abi <solidity-fragment>
set -e

solc_version=$(solc --version)
solc_version=$(<<<"$solc_version" grep ^Version:)
solc_version=${solc_version#* }
solc_version=${solc_version%%+*}

[[ $1 ]] || seth --fail-usage "$0"
input="pragma solidity ^${solc_version}; contract A { $1 }"
json=$(solc --combined-json=abi - <<<"$input")
# Changed from "A" to "<stdin>:A" in solc 0.4.10:
name=$(jshon <<<"$json" -e contracts -k)
abi=$(jshon <<<"$json" -e contracts -e "$name" -e abi -u)
seth --decorate-abi "$abi"
