#!/usr/bin/env bash
set -e

function usage() {
  echo >&2 "Usage: seth --use <spec> <subcommand>..."
  echo >&2 "Example:"
  echo >&2
  echo >&2 "  $ seth --use solc:0.4.11 seth combined-json"
  echo >&2
  exit 1
}

[[ "$#" -gt 0 ]] || usage

shopt -s extglob
case $1 in
  # package spec e.g. solc:0.4.12
  solc:[0-9].+([0-9.]))
    solc="solc-${1#solc:}"
    set +e
    bin="$(type -p "$solc")"
    ;;
  # versioned binary name as used in dapptools, e.g. solc-0.4.12
  solc*)
    solc="$1"
    set +e
    bin="$(type -p "$solc")"
    ;;
  # if there's a '/', interpret as a path
  */*)
    bin="$1"
    ;;
  *)
    echo >&2 "${0##*/}: unrecognized package spec: $1"
    exit 1
esac
shift

[[ "$#" -gt 0 ]] || usage

if [[ -z "$bin" ]]; then
  echo >&2 "${0##*/}: Could not find ${solc} in your path."
  echo >&2 "${0##*/}: Try \`nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.$solc\`"
  echo >&2 "${0##*/}: in your dapptools repo."
  exit 1
else
  set -e
  SOLCBIN="$(realpath -e "${bin}")"
fi

DAPP_SOLC="$SOLCBIN" seth "$@"
