#!/usr/bin/env bash
### seth-bundle-source -- fetch source and compile contract
### Usage: seth bundle-source <address> [<options>]
###
### Requires an etherscan api key
###

# not really sure why this is a list
# seems like we always just want the first element
set -e
SRC=$(seth source "$1" | jq '.[0]')

SOLC_VERSION=$(echo "$SRC" | jq '.CompilerVersion')
SOLC_VERSION=${SOLC_VERSION/'"'}
SOLC_VERSION=${SOLC_VERSION/v}
SOLC_VERSION=${SOLC_VERSION/+*}

SOURCE=$(echo "$SRC" | jq '.SourceCode')
OPT=$(echo "$SRC" | jq '.OptimizationUsed' | seth --show-json)
NAME=$(echo "$SRC" | jq '.ContractName' | seth --show-json)
if [[ "$OPT" -ne  0 ]]; then
    RUNS=$(echo "$SRC" | jq '.Runs')
    export SOLC_FLAGS="--optimize optimize-runs=$RUNS"
fi
    
if [[ "$SETH_DIR" ]]; then
    srcfile="$SETH_DIR"/"$NAME"
else
    srcfile=$(TMPDIR=. mktemp "$NAME".XXXXX)
fi

echo "$SOURCE" | seth --show-json | tr -d '\r' > "$srcfile"
dapp --use solc:"${SOLC_VERSION}" combined-json "$srcfile"
