#!/usr/bin/env bash
### seth---abi-decode -- extract return values from hexdata
### Usage: seth --abi-decode <name>(<in-types>)(<out-types) <hexdata>
###
### Decode <hexdata> according to <out-types> (<in-types> are ignored).
hevm abidecode --abi "$1" --returndata "$2"
