#!/usr/bin/env bash
set -e

function usage() {
  echo >&2 "Usage: seth --use <spec> <subcommand>..."
  echo >&2 "Example:"
  echo >&2
  echo >&2 "  $ seth --use solc:0.4.11 seth combined-json"
  echo >&2
  exit 1
}

[[ "$#" -gt 0 ]] || usage

shopt -s extglob
case $1 in
  solc:[0-9].+([0-9.]))
    version=${1#solc:}
    version=${version//./_}
    override+=" solc = solc-versions.solc_$version;"
    ;;
  *)
    echo >&2 "${0##*/}: unrecognized package spec: $1"
    exit 1
esac
shift

[[ "$#" -gt 0 ]] || usage

seth --nix-run "seth.override {$override}" seth "$@"
