#!/usr/bin/env bash
set -e
data=$(cat)
seth curl "$ETH_RPC_URL" -- -d "$data" -H "Content-Type: application/json" || {
  code=$?
  [[ $code = 7 ]] && sed >&2 <<. "s/^/${0##*/}: /"
Please make sure that you are running a local Ethereum node:
  For example, try running either \`parity' or \`geth --rpc'.
You could also try connecting to an external Ethereum node:
  For example, try \`export ETH_RPC_URL=https://mainnet.infura.io'.
  If you have an Infura API key, add it to the end of the URL.
.
  exit $code
}
