#!/usr/bin/env bash
### seth-publish -- publish an already-signed transaction to the blockchain
### Usage: seth publish [<txdata>]
### Publish a previously signed transaction to the blockchain.
###
### If no <txdata> is given, read it from standard input instead.
set -e
txdata=$(seth --to-hexdata "$@")
jshon+=(-s "$txdata" -i append)
seth rpc eth_sendRawTransaction -- "${jshon[@]}"
