#!/usr/bin/env node
//seth---decode-event -- decode hexdata into event form
const usage = "Usage: seth --decode-event <abi-json> <event-name> <hexdata>";
if (process.argv.length == 5) {
  // silence warnings we don't care about
  const log = console.log
  console.log = () => {};
  const ethers = require("./ethers.min.js");
  console.log = log;
  try {
    const events = new ethers.utils.Interface(process.argv[2]).events;
    console.log(events[process.argv[3]].decode(process.argv[4]).join('\n'))
  } catch (e) {
    console.error(e.toString())
    process.exit(1)
  }
} else {
  console.log(usage)
  process.exit(1)
}
