#!/usr/bin/env bash
### seth---from-wei -- convert a wei amount into ETH
### Usage: seth --from-wei <value> [<unit>]
set -e
[[ $1 ]] || set -- "$(cat)"
[[ $1 ]] || seth --fail-usage "$0"
set -- "$*"
[[ $1 = *" "* ]] || set -- "$1 eth"
number=${1%% *} unit=${1#* }
# shellcheck disable=2018,2019
unit=$(tr A-Z a-z <<<"$unit")

case $unit in
  wei) scale=0;;
  gwei) scale=9;;
  eth|ether) scale=18;;
  *) seth --fail "${0##*/}: error: unrecognized monetary value: \`$1'"
esac

number=${number/[eE]/*10^}
number=${number/^+/^}
bc <<<"scale=$scale; $number * 10^-$scale"
