#!/usr/bin/env bash
### token-supply -- print the total supply of a token
### Usage: token supply <token>
set -e
[ $# = 1 ] || token supply --usage
supply=$(seth call "$1" "totalSupply()(uint)")
token --format "$1" "$supply"
