#!/usr/bin/env bash
### token-balance -- print the token balance of an account
### Usage: token balance <token> <account>
set -e
[ $# = 2 ] || token balance --usage
sig="balanceOf(address)(uint)"
balance=$(seth call "$1" "$sig" "$2")
token --format "$1" "$balance"
