#!/bin/sh -e
### token-transfer -- transfer tokens to one account from another
### Usage: token transfer <token> <destination> <amount> [<source>]
### Perform a `transfer' or (if <source> is given) `transferFrom' operation.
[ $# = 3 ] || [ $# = 4 ] || token transfer --usage
amount=$(token --parse "$3")
if [ $# = 3 ]; then
  sig="transfer(address,uint)(bool)"
  seth send "$1" "$sig" "$2" "$amount"
else
  sig="transferFrom(address,address,uint)(bool)"
  seth send "$1" "$sig" "$4" "$2" "$amount"
fi
