#!/usr/bin/env bash
### token-approve -- set how much one account can transfer from another
### Usage: token approve <token> <spender> <amount>
### Note: <amount> must be an integer representing wei (or equivalent).
set -e
[ $# = 3 ] || token approve --usage
sig="approve(address,uint)(bool)"
seth send "$1" "$sig" "$2" "$3"
