#!/usr/bin/env bash
### token-transfer -- transfer tokens to one account from another
### Usage: token transfer <token> <destination> <amount> [<source>]
### Perform a `transfer' or (if <source> is given) `transferFrom' operation.
set -e
[ $# = 3 ] || [ $# = 4 ] || token transfer --usage
if [ $# = 3 ]; then
  sig="transfer(address,uint)(bool)"
  seth send "$1" "$sig" "$2" "$3"
else
  sig="transferFrom(address,address,uint)(bool)"
  seth send "$1" "$sig" "$4" "$2" "$3"
fi
