#!/usr/bin/env bash
### dapp-uninstall -- remove a smart contract library
### Usage: dapp uninstall <lib>
set -e
dapp --sanity "$0"
for x; do
  (set -x; git rm -r "lib/$x")
  (set -x; git commit -m "dapp uninstall $x")
done
