#!/usr/bin/env bash
### dapp-clone -- clone a github repo
### Usage: dapp clone <org/repo>
set -e
deps=$(dapp --parse-deps "$@")
while read -r _ name url; do
  ssh_url=${url/https:\/\/github.com\//git@github.com:}
  (set -x; git clone "$ssh_url" "$name" --recursive)
done <<<"$deps"
