#!/usr/bin/env bash
### dapp pkg -- use the dapp package manager
### Usage: dapp pkg [<command>] [<arg>...]

set -e

if [[ ! -d "$DAPPTOOLS" ]]; then
  [ "$1" = init ] || {
    echo "Please run \`dapp pkg init\`"
    exit 1
  }
fi

case $1 in
  init) {
    curl -sS https://dapp.tools/install | sh
  };;
  list|ls) {
    cd "$DAPPTOOLS"
    mapfile -t installed < <(nix-env -q)
    echo "${installed[@]}"
  };;
  selfupdate|self-update) {
    echo "Updating dapptools..."
    cd "$DAPPTOOLS"
    git pull
    nix-env -f . -iA dapp
  };;
  install|update) {
    shift
    cd "$DAPPTOOLS"
    git pull
    nix-env -f . -iA "$@"
  };;
  uninstall|remove) {
    shift
    nix-env -e "$@"
  };;
  *) {
    echo "dapp package manager..."
    echo "current directory: $DAPPTOOLS"
    echo ""
    echo "Options:"
    echo "  init"
    echo "  list"
    echo "  install <package>"
    echo "  uninstall <package>"
    echo "  selfupdate"
  }
esac
