#!/usr/bin/env bash
### dapp-test -- run the test suite
### Usage: dapp test [<options>]
###
### Options:
###   -v, --verbose         trace ouput for failing tests
###   -vv                   trace output for all tests including passes
###   -m, --match=<string>  only run test methods matching regex
###
### RPC options:
###   --rpc                 fetch remote state via ETH_RPC_URL
###   --rpc-url=<url>       fetch remote state via <url>
###   --rpc-block=<number>  block number (latest if not specified)
set -e
have() { command -v "$1" >/dev/null; }

have hevm || {
  echo >&2 "${0##*/}: error: \`hevm' not found"
  echo >&2 "${0##*/}: error: please install it and try again"
  exit 1
}

if ! [[ $DAPP_SKIP_BUILD ]] ; then
  DAPP_LINK_TEST_LIBRARIES=1 dapp build || exit
fi

if [ "$DAPP_VERBOSE" ]; then set -x; fi

state=$(dapp --make-library-state)
function clean() { rm -rf "$state"; }
trap clean EXIT

opts=$(dapp --hevm-opts "$0" "$@")
# shellcheck disable=SC2068
hevm dapp-test --json-file="${DAPP_JSON}" --dapp-root=. --state="$state" ${opts[@]}
