#!/usr/bin/env bash
set -ex; tmp=$(mktemp -d); cd "$tmp"

# Try initializing and testing a new dapp
( mkdir foo; cd foo; dapp init )

# Try testing a bunch of dappsys packages
dappsys() {
  git clone https://github.com/dapphub/"$1" --recursive
  ( cd "$1" && dapp test )
}

dappsys ds-auth
# dappsys ds-cache # No test suite
dappsys ds-exec
dappsys ds-guard
dappsys ds-math
# dappsys ds-multisig # Incompatible with Solidity 0.5
dappsys ds-note
dappsys ds-proxy
dappsys ds-roles
dappsys ds-stop
dappsys ds-thing
dappsys ds-token
# dappsys ds-value # No test suite
dappsys ds-vault
