#!/usr/bin/env node

console.log(buildRemappings(".").join("\n"))

function buildRemappings(prefix) {
  const lib = `${prefix}/${process.env.DAPP_LIB}`
  const ctx = `${prefix}/${process.env.DAPP_SRC}`

  const remappings = ls(lib).map(name => {
    return `${normalize(ctx)}:${name}/=${normalize(lib)}/${name}/${process.env.DAPP_SRC}/`
  })

  return ls(lib).map(name => {
    return buildRemappings(`${lib}/${name}`)
  }).concat(remappings).flat()
}

// strip the leading `.` or `./` from a path
function normalize(path) {
  return path.replace(/^\.\//, "").replace(/^\//, "")
}

function ls(dir) {
  try {
    return require("fs").readdirSync(dir).sort()
  } catch (error) {
    return []
  }
}

