#!/usr/bin/env bash
### dapp-test-standalone -- test a standalone .sol file with ds-test
### Usage: dapp test-standalone foo.t.sol

set -e

if [ -z "$DAPPSYS_PATH" ]; then
  >&2 echo "dapp test-standalone: \$DAPPSYS_PATH must point to dappsys root"
  >&2 echo "dapp test-standalone: containing at least ds-test/src/test.sol"
  exit 1
fi

tmp=$(mktemp -d)
mkdir "$tmp"/{src,lib}
cp "$1" "$tmp"/src
cp -r "$DAPPSYS_PATH"/* "$tmp"/lib
cd "$tmp"
DAPP_IGNORE_HASHES=1 dapp test
