#!/usr/bin/env bash
### dapp-install -- install a smart contract library
### Usage: dapp install <lib>
### <lib> may be:
###   - a Dapphub repo (ds-foo)
###   - the URL of a Dapphub repo (https://github.com/dapphub/ds-foo)
###   - a path to a repo in another Github org (org-name/repo-name)
set -e

dapp --sanity "$0"
deps=$(dapp --parse-deps "$@")
if [[ -z "$deps" ]]; then
  dapp help install
  exit
fi

while read -r unparsed name url; do
  # get the tag/branch/rev from the repo name if it's specified after the URL with
  # an '@' delimiter.
  IFS='@' read -ra repo <<< "$name"
  name=${repo[0]}
  if [ -z ${repo[1]+x} ]; then
      params="--set-branch ${repo[1]}";
  else
      params=""
  fi

  (set -x; git submodule add --force "$params" "$url" "lib/$name")
  (set -x; git submodule update --init --recursive "lib/$name")
  (set -x; git commit -m "dapp install $unparsed")
done <<<"$deps"
