#!/usr/bin/env bash
set -e

# Uses the output of dapp test to compare with dapp --snapshot
DIFF="$(diff .gas-snapshot <(dapp test | grep 'gas:' | cut -d " " -f 2-4) || true)"
if [ -n "$DIFF" ]
then
   echo "$DIFF"
   exit 1
fi