#!/usr/bin/env bash
### dapp-init -- bootstrap a new dapp
### Usage: dapp init
set -e -o noclobber
[[ -e .git ]] && dapp --sanity "$0"

solc_version=$(solc --version)
solc_version=$(<<<"$solc_version" grep ^Version:)
solc_version=${solc_version#* }
solc_version=${solc_version%%+*}

create() { [[ -e $1 ]] || { cat >"$1"; (set -x; git add "$1"); }; }
insert() {
  touch "$1"
  while read -r line; do
    grep -qF "$line" "$1" || printf >>"$1" '%s\n' "$line"
  done
  (set -x; git add "$1")
}

(set -x; git init)
(set -x; mkdir -p lib src)

insert .gitignore <<.
/out
.

create .gitattributes <<.
*.sol linguist-language=Solidity
.

name=$(basename "$(pwd)")
name=$(<<<"$name" tr '[:upper:]' '[:lower:]')
IFS=" " read -r -a nouns <<<"${name//[^a-z]/ }"
noun=${nouns[$((${#nouns[@]} - 1))]}
type=$(<<<"$name" perl -pe 's/(\w+)/\u$1/g')
type=$(<<<"$type" tr -cd a-zA-Z0-9)
type=${1-$type}

create Makefile <<.
all    :; dapp build
clean  :; dapp clean
test   :; dapp test
deploy :; dapp create $type
.

create "src/$type.sol" <<.
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^${solc_version};

contract $type {
}
.

create "src/$type.t.sol" <<.
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^${solc_version};

import "ds-test/test.sol";

import "./$type.sol";

contract ${type}Test is DSTest {
    $type $noun;

    function setUp() public {
        $noun = new $type();
    }

    function testFail_basic_sanity() public {
        assertTrue(false);
    }

    function test_basic_sanity() public {
        assertTrue(true);
    }
}
.

git add -A
(set -x; git commit -m "dapp init $type")
(set -x; dapp install ds-test)
(set -x; DAPP_REMAPPINGS="$(dapp-remappings)" make test)
