#!/usr/bin/env bash
set -ex; tmp=$(mktemp -d); cd "$tmp"

# Try initializing and testing a new dapp
( mkdir foo; cd foo; dapp init )

# Try testing a bunch of dappsys packages
dappsys() {
  git clone https://github.com/dapphub/"$1" --recursive
  ( cd "$1" && dapp test )
}

dapp ds-auth
# dapp ds-cache # No test suite
dapp ds-exec
dapp ds-guard
dapp ds-math
dapp ds-multisig
dapp ds-note
dapp ds-proxy
dapp ds-roles
dapp ds-stop
dapp ds-thing
dapp ds-token
# dapp ds-value # No test suite
dapp ds-vault
