#!/usr/bin/env bash
caller=$1; shift

fail () {
  cmd=${caller#*-}
  echo >&2 "${caller##*/}: error: $1" && echo >&2
  dapp help "$cmd" >&2
  exit 1
}

opts=()
[[ "$DAPP_TEST_FFI" ]]            && opts+=(--ffi)
[[ "$DAPP_TEST_SMTDEBUG" ]]       && opts+=(--smtdebug)
[[ "$DAPP_TEST_COVERAGE" ]]       && opts+=(--coverage)
[[ "$DAPP_TEST_DEPTH" ]]          && opts+=(--depth "$DAPP_TEST_DEPTH")
[[ "$DAPP_TEST_CACHE" ]]          && opts+=(--cache "$DAPP_TEST_CACHE")
[[ "$DAPP_TEST_MATCH" ]]          && opts+=(--match "$DAPP_TEST_MATCH")
[[ "$DAPP_TEST_SOLVER" ]]         && opts+=(--solver "$DAPP_TEST_SOLVER")
[[ "$DAPP_TEST_REPLAY" ]]         && opts+=(--replay "$DAPP_TEST_REPLAY")
[[ "$DAPP_TEST_VERBOSITY" ]]      && opts+=(--verbose "$DAPP_TEST_VERBOSITY")
[[ "$DAPP_TEST_COV_MATCH" ]]      && opts+=(--cov-match "$DAPP_TEST_COV_MATCH")
[[ "$DAPP_TEST_FUZZ_RUNS" ]]      && opts+=(--fuzz-runs "$DAPP_TEST_FUZZ_RUNS")
[[ "$DAPP_TEST_SMTTIMEOUT" ]]     && opts+=(--smttimeout "$DAPP_TEST_SMTTIMEOUT")
[[ "$DAPP_TEST_MAX_ITERATIONS" ]] && opts+=(--max-iterations "$DAPP_TEST_MAX_ITERATIONS")



if [[ "$HEVM_RPC" == "yes" ]]; then
  number=${DAPP_TEST_NUMBER:-latest}
  echo >&2 "${caller##*/}: rpc block: $number"
  b=$(seth block "$number")
  n=$(seth --field number <<< "$b") && export DAPP_TEST_NUMBER=$n
  t=$(seth --field timestamp <<< "$b") && export DAPP_TEST_TIMESTAMP=$t
  opts+=(--rpc "$ETH_RPC_URL")
fi

echo "${opts[@]}"
