#!/usr/bin/env bash
set -e

opts=()

while [[ $# -gt 0 ]]; do
  opt=$1; shift
  case $opt in
    -r|--regex)
      opts+=(--match "$1"); shift
      ;;
    -vv)
      opts+=(--verbose 2);
      ;;
    -v|--verbose)
      opts+=(--verbose 1);
      ;;
    *)
      echo >&2 "dapp-test-hevm: unknown argument: $opt"
      exit 1
      ;;
  esac
done

if [ "$DAPP_VERBOSE" ]; then set -x; fi

state=$(dapp --make-library-state)
function clean() { rm -rf "$state"; }
trap clean EXIT

hevm dapp-test --json-file="${DAPP_JSON}" --dapp-root=. --state="$state" "${opts[@]}"
