#!/usr/bin/env bash
caller=$1; shift

fail () {
  cmd=${caller#*-}
  echo >&2 "${caller##*/}: error: $1" && echo >&2
  dapp help "$cmd" >&2
  exit 1
}

opts=()

while [[ $1 ]]; do
  case $1 in
    --)
      shift; break;;
    -m|--match)
      shift; [ -n "$1" ] || fail "--match requires an argument."
      opts+=(--match "$1"); shift
      ;;
    -vvv)
      opts+=(--verbose 3); shift
      ;;
    -vv)
      opts+=(--verbose 2); shift
      ;;
    -v|--verbose)
      opts+=(--verbose 1); shift
      ;;
    --fuzz-runs)
      shift; [ -n "$1" ] || fail "--fuzz-runs requires an argument."
      opts+=(--fuzz-runs "$1"); shift
      ;;
    --smttimeout)
      shift; [ -n "$1" ] || fail "--smttimeout requires an argument."
      opts+=(--smttimeout "$1"); shift
      ;;
    --solver)
      shift; [ -n "$1" ] || fail "--solver requires an argument."
      opts+=(--solver "$1"); shift
      ;;
    --max-iterations)
      shift; [ -n "$1" ] || fail "--max-iterations requires an argument."
      opts+=(--max-iterations "$1"); shift
      ;;
    --replay)
      shift; [ -n "$1" ] || fail "--replay requires an argument."
      opts+=(--replay "$1"); shift
      ;;
    --rpc-url)
      shift; [ -n "$1" ] || fail "--rpc-url requires an argument."
      HEVM_RPC=yes
      export ETH_RPC_URL=$1; shift
      ;;
    --rpc-block)
      shift; [ -n "$1" ] || fail "--rpc-block requires an argument."
      HEVM_RPC=yes
      export DAPP_TEST_NUMBER=$1; shift
      ;;
    --rpc)
      [ -n "$ETH_RPC_URL" ] || fail "ETH_RPC_URL not set."
      shift; HEVM_RPC=yes
      ;;
    --cache)
      shift; [ -n "$1" ] || fail "--cache requires a path to a cache dir"
      opts+=(--cache "$1"); shift
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

if [[ "$HEVM_RPC" == "yes" ]]; then
  number=${DAPP_TEST_NUMBER:-latest}
  echo >&2 "${caller##*/}: rpc block: $number"
  b=$(seth block "$number")
  n=$(seth --field number <<< "$b") && export DAPP_TEST_NUMBER=$n
  t=$(seth --field timestamp <<< "$b") && export DAPP_TEST_TIMESTAMP=$t
  opts+=(--rpc "$ETH_RPC_URL")
fi

echo "${opts[@]}"
