#!/usr/bin/env bash
### dapp-build -- compile the source code
### Usage: dapp build [--extract]
###
###  --extract:  After building, write the .abi, .bin and .bin-runtime. Implies `--legacy`
###              files from the solc json into $DAPP_OUT. Beware of contract
###              name collisions. This is provided for compatibility with older
###              workflows.
###  --optimize: activate the solidity optimizer.
###  --via-ir    change compilation pipeline to go through the Yul intermediate representation
###  --legacy:   Compile using the `--combined-json` flag. Some options are
###              missing from this format. This is provided for compatibility with older
###              workflows.
set -e

info() {
  while [[ $# -gt 0 ]]; do
    opt=$1; shift
    case $opt in
      -*)
        FLAGS=$opt;
        ;;
      *)
        ARGS=$opt;
        ;;
    esac
  done
  echo >&2 "$FLAGS" "${0##*/}: $ARGS"
}

colorize() {
    awk '{
gsub("Warning:", "\033[1;33m&\033[0m");
gsub(".*Error:", "\033[1;31m&\033[0m");
print }'
}

cd "$DAPP_ROOT"

# use a custom path if DAPP_SOLC is set
export SOLC=${DAPP_SOLC:-solc}

if [ "$DAPP_LINK_TEST_LIBRARIES" = 1 ]; then
    sender=0x00a329c0648769a73afac7f9381e08fb43dbea72
    nonce=48576
    mapfile -t libraries < <(dapp --find-libraries)

    if [[ ${#libraries[@]} -gt 0 ]]; then

        info "building with linked libraries"
        for lib in "${libraries[@]}"; do
            address=$(dapp address "$sender" "$nonce")
            links+=" $lib:$address"
            ((nonce++))
        done
    fi
else
    (set -x; dapp clean)
fi

export -f info
export DAPP_LIBRARIES=${DAPP_LIBRARIES-"$links"}

mkdir -p "$DAPP_OUT"

if [[ -z "$DAPP_BUILD_LEGACY" && -z "$DAPP_BUILD_EXTRACT" ]]; then
    if [[ "$SOLC_FLAGS" ]]; then
        info "warning: SOLC_FLAGS are only recognized using '--legacy'"
        info "consider using --optimize or a custom standard-json instead."
    fi
    if [[ "$DAPP_STANDARD_JSON" ]]; then
        "$SOLC" --allow-paths . --standard-json < "$DAPP_STANDARD_JSON" > "$DAPP_JSON"
    else
        dapp mk-standard-json | "$SOLC" --standard-json --allow-paths . > "$DAPP_JSON"
    fi

    # pipe errors to stderr
    jq -r 'if .errors then .errors | map(."formattedMessage") | @sh else empty end' "$DAPP_JSON" \
        | sed -e "s/' //g" -e "s/'//g" -e 's/\\\(.\)\\/\1 /g' | colorize 1>&2
    # if sources is empty, the compilation failed
    [[ $(jq -r '.sources' "$DAPP_JSON") = "null" ||  $(jq -r '.sources' "$DAPP_JSON") = {} ]] && exit 1 || exit 0

else
    info "warning: legacy builds are deprecated and might not work with other dapp commands"
    dapp build-legacy
fi
