#!/usr/bin/env bash
### dapp-install -- install a smart contract library
### Usage: dapp install <lib>
### <lib> may be:
###   - a Dapphub repo (ds-foo)
###   - the URL of a Dapphub repo (https://github.com/dapphub/ds-foo)
###   - a path to a repo in another Github org (org-name/repo-name)
set -e

dapp --sanity "$0"
deps=$(dapp --parse-deps "$@")
if [[ -z "$deps" ]]; then
  dapp help install
  exit
fi

while read -r unparsed name url; do
  # get the tag/branch/rev from the repo name if it's specified after the URL with
  # an '@' delimiter.
  IFS='@' read -ra repo <<< "$url"
  url=${repo[0]}
  tag=${repo[1]}
  # strip the tag from the name
  name=${name%@*}

  (set -x; git submodule add --force "$url" "lib/$name")
  (set -x; git submodule update --init --recursive "lib/$name")
  if [ "$tag" ]; then
    # checkout the tag
    (set -x; cd "lib/$name" && git checkout --recurse-submodules "$tag" && cd -)
    git add "lib/$name"
  fi
  (set -x; git commit -m "dapp install $unparsed")
done <<<"$deps"
