#!/usr/bin/env bash
### dapp -- command-line Ethereum dapp tools
### Usage: dapp <command> [<args>]
###    or: dapp help <command>
###
### Build, test, deploy and transact with Ethereum contracts from the comfort of your command line.
###

set -e

export DAPPTOOLS=${DAPPTOOLS-~/.dapp/dapptools}
export DAPP_SRC=${DAPP_SRC-src}
export DAPP_LIB=${DAPP_LIB-lib}
export DAPP_OUT=${DAPP_OUT-out}

set -e

if ! [[ $DAPP_INIT ]]; then
  export DAPP_INIT=1
  # shellcheck source=/dev/null
  [[ -e ~/.dapprc ]] && . ~/.dapprc
  # shellcheck source=/dev/null
  [[ $(pwd) != ~ && -e .dapprc ]] && . .dapprc
fi

if [[ $2 = --help ]]; then
  exec "${0##*/}" help -- "$1"
elif [[ $DAPP_SOLC_VERSION ]]; then
  v=$DAPP_SOLC_VERSION
  unset DAPP_SOLC_VERSION
  exec "${0##*/}---use" "solc:$v" "${@:1}"
elif [[ $1 = -* ]] && command -v "${0##*/}-$1" &>/dev/null; then
  exec "${0##*/}-$1" "${@:2}"
fi

"${0##*/}-${1-help}" "${@:2}"
