#!/usr/bin/env bash
### dapp-test -- run the test suite
### Usage: dapp test [-v[v]]
###
### By default, dapp test outputs failed assertions only.
### -v increases verbosity to include the full trace of failing tests.
### -vv outputs traces for all tests, including successful ones.
set -e
have() { command -v "$1" >/dev/null; }

if ! [[ $DAPP_SKIP_BUILD ]] ; then
  DAPP_LINK_TEST_LIBRARIES=1 dapp build || exit
fi

have hevm   && ! [[ $DAPP_NO_HEVM   ]] && dapp test-hevm   "$@"

have hevm || {
  echo >&2 "${0##*/}: error: \`hevm' not found"
  echo >&2 "${0##*/}: error: please install it and try again"
  exit 1
}
