name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
        include:
          - os: ubuntu-latest
            apt-get: autoconf automake libtool
          - os: macos-latest
            brew: automake

    steps:
      - name: Workaround for actions/cache#403
        if: runner.os == 'macOS'
        run: |
          brew install gnu-tar
          echo PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH" >> $GITHUB_ENV

      - name: Get Packages
        uses: mstksg/get-package@v1
        with:
          brew: ${{ matrix.brew }}
          apt-get: ${{ matrix.apt-get }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'

      - name: Cache Local
        id: cache-local
        uses: actions/cache@v1
        with:
          path: ~/.local/
          key: ${{ runner.os }}-local-v3

      - name: Cache Stack
        id: cache-stack
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-v3

      - name: Cache Cabal
        id: cache-cabal
        uses: actions/cache@v1
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-cabal-v3

      - name: Build Binaries
        run: |
          .github/scripts/install-solc.sh
          .github/scripts/install-z3.sh
          .github/scripts/install-cvc4.sh
        env:
          HOST_OS: ${{ runner.os }}

      - name: Build Libraries
        run: |
          .github/scripts/install-libsecp256k1.sh
          .github/scripts/install-libff.sh
        env:
          HOST_OS: ${{ runner.os }}

      - name: Build Dependencies
        run: |
          cd src/hevm && stack build --ghc-options="-Werror" --extra-include-dirs=$HOME/.local/include --extra-lib-dirs=$HOME/.local/lib --only-dependencies && cd ../..

      - name: Build and install hevm
        run: |
          cd src/hevm && stack install --extra-include-dirs=$HOME/.local/include --extra-lib-dirs=$HOME/.local/lib && cd ../..

      - name: Test
        if: runner.os == 'macOS'
        run: |
          export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:$HOME/.local/lib"
          export PATH="${PATH}:$HOME/.local/bin"

          cp "$HOME/.local/bin/solc-0.6.12" "$HOME/.local/bin/solc"
          cd src/hevm && stack test --extra-include-dirs=$HOME/.local/include --extra-lib-dirs=$HOME/.local/lib && cd ../..

      - name: Amend and compress binaries (macOS)
        if: runner.os == 'macOS'
        run: .github/scripts/build-macos-release.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: hevm-${{ runner.os }}
          path: hevm.tar.gz
